//
// Created by mhmoritz3 on 07.05.19.
//

#ifndef EMBEDDEDSYSTEMSPROJECT_INSTANCEMANAGER_H
#define EMBEDDEDSYSTEMSPROJECT_INSTANCEMANAGER_H


class InstanceManager {

};


#endif //EMBEDDEDSYSTEMSPROJECT_INSTANCEMANAGER_H
